
### Welcome page
//@no-log
GET http://localhost:9001/

### Add new Book
//@no-log
POST http://localhost:9001/books
content-type: application/json

{
"author": "Kevin Schnider",
"title": "Northern Lights",
"isbn": "1234567891",
"price": "9.90"
}

### Try to add new Book with missing values
//@no-log
POST http://localhost:9001/books
content-type: application/json

{
  "isbn": "1234567891",
  "price": "9.90"
}

### Get all Books
//@no-log
GET http://localhost:9001/books

### Delete Book
//@no-log
DELETE http://localhost:9001/books/1234567891