server:
  port: 9001
  tomcat:
      connection-timeout: 2s # // The maximum time to wait for a connection from the pool
      keep-alive-timeout: 15s # // The number of seconds to wait for an HTTP request to complete before closing the connection
      threads:
        max: 50
        min-spare: 5 # // Always running and created  at startup

spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1

management:
  endpoints:
    web:
      exposure:
        include: refresh
polar:
  greeting: Welcome to the local book catalog!




